# Generated by Django 4.2.7 on 2024-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_project_vote_ratio_project_vote_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_Link',
            new_name='demo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='features_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
